/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['model.js']) {
  _$jscoverage['model.js'] = [];
  _$jscoverage['model.js'][1] = 0;
  _$jscoverage['model.js'][2] = 0;
  _$jscoverage['model.js'][3] = 0;
  _$jscoverage['model.js'][4] = 0;
  _$jscoverage['model.js'][5] = 0;
  _$jscoverage['model.js'][6] = 0;
  _$jscoverage['model.js'][7] = 0;
  _$jscoverage['model.js'][8] = 0;
  _$jscoverage['model.js'][9] = 0;
  _$jscoverage['model.js'][10] = 0;
  _$jscoverage['model.js'][11] = 0;
  _$jscoverage['model.js'][12] = 0;
  _$jscoverage['model.js'][17] = 0;
}
_$jscoverage['model.js'][1]++;
(function () {
  _$jscoverage['model.js'][2]++;
  var Model;
  _$jscoverage['model.js'][3]++;
  module.exports = Model = (function () {
  _$jscoverage['model.js'][4]++;
  function Model() {
}
  _$jscoverage['model.js'][5]++;
  Model.prototype.data = [];
  _$jscoverage['model.js'][6]++;
  Model.prototype["new"] = (function () {
});
  _$jscoverage['model.js'][7]++;
  Model.prototype.save = (function () {
});
  _$jscoverage['model.js'][8]++;
  Model.prototype.update = (function () {
});
  _$jscoverage['model.js'][9]++;
  Model.prototype["delete"] = (function () {
});
  _$jscoverage['model.js'][10]++;
  Model.prototype.all = (function () {
});
  _$jscoverage['model.js'][11]++;
  Model.prototype.getBy = (function (param, value) {
  _$jscoverage['model.js'][12]++;
  return ({param: param, value: value});
});
  _$jscoverage['model.js'][17]++;
  return Model;
})();
}).call(this);
_$jscoverage['model.js'].source = ["(function() {","  var Model;","  module.exports = Model = (function() {","    function Model() {}","    Model.prototype.data = [];","    Model.prototype[\"new\"] = function() {};","    Model.prototype.save = function() {};","    Model.prototype.update = function() {};","    Model.prototype[\"delete\"] = function() {};","    Model.prototype.all = function() {};","    Model.prototype.getBy = function(param, value) {","      return {","        param: param,","        value: value","      };","    };","    return Model;","  })();","}).call(this);"];
