/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['mongorm.js']) {
  _$jscoverage['mongorm.js'] = [];
  _$jscoverage['mongorm.js'][1] = 0;
  _$jscoverage['mongorm.js'][2] = 0;
}
_$jscoverage['mongorm.js'][1]++;
(function () {
  _$jscoverage['mongorm.js'][2]++;
  module.exports = {Model: require("./model")};
}).call(this);
_$jscoverage['mongorm.js'].source = ["(function() {","  module.exports = {","    Model: require('./model')","  };","}).call(this);"];
